# Generated by Django 4.2.4 on 2023-10-25 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AccountPayableReceivable', '0005_alter_invoice_customer_alter_invoice_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=50)),
                ('entity_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaxAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority_name', models.CharField(max_length=50)),
                ('jurisdiction', models.CharField(max_length=50)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_name', models.CharField(max_length=50)),
                ('rate_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_type', models.CharField(max_length=50)),
                ('return_period', models.CharField(max_length=50)),
                ('submitted_date', models.DateField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TaxTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(max_length=50)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountPayableReceivable.customer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountPayableReceivable.supplier')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaxManagementandcompliance.taxrate')),
            ],
        ),
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaxManagementandcompliance.taxtype')),
            ],
        ),
        migrations.CreateModel(
            name='TaxJurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_name', models.CharField(max_length=50)),
                ('tax_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaxManagementandcompliance.taxauthority')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaxManagementandcompliance.taxrate')),
            ],
        ),
        migrations.CreateModel(
            name='TaxInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountPayableReceivable.customer')),
                ('items', models.ManyToManyField(related_name='invoices', to='AccountPayableReceivable.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='TaxExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaxManagementandcompliance.entity')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaxManagementandcompliance.taxtype')),
            ],
        ),
        migrations.CreateModel(
            name='TaxDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('deduction_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaxManagementandcompliance.entity')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaxManagementandcompliance.taxtype')),
            ],
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_name', models.CharField(max_length=50)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaxManagementandcompliance.taxrate')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaxManagementandcompliance.taxtype')),
            ],
        ),
        migrations.CreateModel(
            name='TaxComplianceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('document_number', models.CharField(max_length=20)),
                ('document_date', models.DateField()),
                ('description', models.TextField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaxManagementandcompliance.entity')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaxManagementandcompliance.taxtype')),
            ],
        ),
    ]
