# Generated by Django 4.2.4 on 2023-10-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaxManagementandcompliance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxtransaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='taxtransaction',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='taxtransaction',
            name='tax_rate',
        ),
        migrations.DeleteModel(
            name='TaxInvoice',
        ),
        migrations.DeleteModel(
            name='TaxTransaction',
        ),
    ]
