# Generated by Django 4.2.4 on 2023-10-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountPayableReceivable', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccountPayableReceivable.customer'),
        ),
    ]
