# Generated by Django 4.2.4 on 2023-10-23 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AccountPayableReceivable', '0003_alter_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AccountPayableReceivable.supplier'),
        ),
    ]
