# Generated by Django 4.2.4 on 2023-10-25 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Financialreportinganalytics', '0001_initial'),
        ('AccountPayableReceivable', '0005_alter_invoice_customer_alter_invoice_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('financial_summary', 'Financial Summary'), ('invoice_summary', 'Invoice Summary'), ('payment_summary', 'Payment Summary')], max_length=20)),
                ('report_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('xlsx', 'Excel')], max_length=10)),
                ('report_criteria', models.TextField()),
                ('invoice_date_range', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoices', models.ManyToManyField(related_name='associated_reports', to='AccountPayableReceivable.invoice')),
                ('payments', models.ManyToManyField(related_name='associated_reports', to='AccountPayableReceivable.payment')),
                ('transactions', models.ManyToManyField(related_name='associated_reports', to='Financialreportinganalytics.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Financialreportinganalytics.financialaccount'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Financialreportinganalytics.financialaccount'),
        ),
        migrations.CreateModel(
            name='ReportPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=10)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccountPayableReceivable.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
